### ISSUE TITLE
Extract Data from Multiple Sources

### ISSUE THREAD

**Issue by sujitdebnath** [sujitdebnath/fau-data-engineering-ss23#1]
Set up an automated process to extract the bicycle traffic and weather data in Köln from two data sources, [mobilithek](https://mobilithek.info/) and [meteostat](https://meteostat.net/en/). This issue involves identifying the best data extraction method, validating the quality of the extracted data, and automating the extraction process.

**Comment by sujitdebnath** [comment]
**Task List:**
- [x] Configure Python package manager [PDM](https://pdm.fming.dev/) for the project and exercises.
- [x] Prepare the skeleton for developing the data pipeline.
- [x] Create a modularized structure of the ETL pipeline.
- [x] Implement necessary helping methods for extracting data.
- [x] Develop a script for extracting data from multiple sources.
