### ISSUE TITLE
Final Report and Presentation Submission

### ISSUE THREAD

**Issue by sujitdebnath** [sujitdebnath/fau-data-engineering-ss23#6]
This issue is to track the tasks related to the submission of the final report and optional project presentation.

**Task List:**
- [x] Work on the final report in Jupyter Notebook format (`report.ipynb`) or export as a PDF (`report.pdf`) or HTML (`report.html`).
- [x] Commit and push the final report file to the `/project` directory on GitHub.
- [x] Prepare optional project presentation slides (`slides.pdf`) and make sure the presentation slides cover the data science question, data sources, and report (excluding implementation details of the data pipeline).
- [x] Commit and push the presentation slides to the `/project` directory on GitHub.
